<a href="https://colab.research.google.com/github/najub/Python-Data-Science/blob/main/Python_Data_Science_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assunto é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [ ]:
!python -V

Python 3.6.9


# 1.3 Trabalhando com arrays Numpy

In [ ]:
import numpy as np

In [ ]:
km = np.loadtxt('carros-km.txt')

In [ ]:
km

In [ ]:
years = np.loadtxt('carros-anos.txt')

In [ ]:
years

In [ ]:
years = np.loadtxt('carros-anos.txt', dtype = int)

In [ ]:
years

### Obtendo a quilometragem média por ano

In [ ]:
km_year = km / (2019 - years)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
km_year

# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [14]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

### Importando todo o pacote e atribuindo um novo nome 

In [ ]:
import numpy as np

### Importando parte do pacote

In [16]:
from numpy import arange

# 5.1 Criando arrays Numpy

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [20]:
km_from_list = np.array([2300, 4350, 3405, 678])

In [23]:
km_from_list

array([2300, 4350, 3405,  678])

In [22]:
type(km_from_list)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [28]:
km_external = np.loadtxt('carros-km.txt', int)

In [29]:
km_external

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [31]:
km_external.dtype

dtype('int64')

### Arrays com duas dimensões

In [32]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [34]:
Acessorios = np.array(dados)
Acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [36]:
km_external.shape 


(258,)

In [37]:
Acessorios.shape #linha,coluna

(3, 8)

### Comparando desempenho com listas

In [38]:
np_array = np.arange(1000000)

In [41]:
py_list = list(range(1000000))

In [40]:
%time for _ in range(100): np_array*=2

CPU times: user 73.3 ms, sys: 0 ns, total: 73.3 ms
Wall time: 76.8 ms


In [42]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 7.71 s, sys: 1.55 s, total: 9.26 s
Wall time: 9.29 s


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [ ]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [44]:
# idade = 2019 - anos

In [45]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [46]:
idade = 2019 - anos

In [47]:
idade

array([16, 28, 29,  0, 13])

### Operações entre arrays

In [51]:
km_media = km / idade

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [52]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

### Operações com arrays de duas dimensões

In [54]:
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [57]:
km_media = dados[0] / (2019 - dados[1])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [58]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [59]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [60]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
contador[5] #quero o item 6

5

In [62]:
contador[-1]

9

In [63]:
dados[1][2]

1990.0

In [64]:
dados[1,2]

1990.0

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

In [65]:
dados[1][2]

1990.0

In [66]:
dados[1,2]

1990.0

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [67]:
contador[1:4] #pegar os elementos de 1 ao 3

array([1, 2, 3])

In [68]:
contador[1:8:2] #pegar os elementos ímpares do 1 ao 7

array([1, 3, 5, 7])

In [70]:
contador[::2] #pegar os elementos pares do array

array([0, 2, 4, 6, 8])

In [71]:
contador[1::2] #pegar os elementos [ímpares] do array

array([1, 3, 5, 7, 9])

In [72]:
dados[:,1:4] #pegar todas as linhas entre o 1° e o 3°

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [73]:
dados[:, 1:3][0]/(2019 - dados[:,1:3][1]) #calcular a velocidade médiad e dois veículos

array([ 204.        , 1280.10344828])

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [74]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [77]:
contador[contador > 5]

array([6, 7, 8, 9])

In [64]:
#calcular a quilometragem média dos veículos fabricados apos o ano 2000

In [79]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [80]:
dados[:, dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [81]:
dados[:, dados[1] > 2000][0] / (2019 - dados[:, dados[1] > 2000][1])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([2775.625     ,           nan, 1981.30769231])

# 5.4 Atributos e métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [82]:
dados = np.array([[44410.,  5712., 37123.,     0., 25757.], [ 2003.,  1991.,  1990.,  2019.,  2006.]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

In [83]:
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [84]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [85]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [86]:
dados.dtype

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [87]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [88]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [89]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [91]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
contador.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [96]:
contador.reshape((5,2), order='C') #C

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [95]:
contador.reshape((5,2), order='F') #Fortran

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [101]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [102]:
info_cars = km + anos
info_cars

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [104]:
np.array(info_cars).reshape(2,5)

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [110]:
np.array(info_cars).reshape((5,2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

In [108]:
np.array(info_cars).reshape(2,5).T

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [111]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [114]:
dados_new.resize((3,5), refcheck=False)
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [115]:
dados_new[2] = dados_new[0] / (2019 - dados_new[1])
dados_new

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

# 5.5 Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [119]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [120]:
anos.shape

(258,)

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [124]:
dataset = np.column_stack((anos, km, valor))

In [125]:
dataset.shape

(258, 3)

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [126]:
np.mean(dataset)

48489.14648578811

In [129]:
np.mean(dataset, axis = 0) #a média de cada coluna

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [130]:
np.mean(dataset[:, 1])

44499.41472868217

In [132]:
np.mean(dataset[:, 2])

98960.51310077519

In [134]:
np.mean(dataset[:, 1:], axis = 0, dtype = int)

array([44499, 98960])

In [147]:
dataset.mean(axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [136]:
np.std(dataset[:, 1:], axis = 0)

array([39859.82699005, 29754.10115039])

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [139]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [142]:
dataset[:, 1].sum(axis=0)

11480849.0

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [143]:
np.sum(dataset, axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [145]:
np.sum(dataset[:, 2])

25531812.38